### ISSUE TITLE
How to get flow data and corresponding txt file?

### ISSUE THREAD

**Issue by duduheihei** [papermsucode/mutual-modality-learning#1]
Hi, I want to run your code, however the source code only provides scripts to generate jpgs and RGB image txt named "train_videofolder.txt" in "dataset_config.py". I wonder how to generate flow map from something-somoething-v2 datase, and how ti generate "train_videofolder_flow.txt". Could you give me some advice?
Here is the code that need txt files mentioned above:
`
    for moda in modality:
        if moda == 'RGB' or moda == 'RGBDiff':
            root_data.append(ROOT_DATASET + 'Something-Something-v2/images')
            filename_imglist_train.append('Something-Something-v2/lists/train_videofolder.txt')
            filename_imglist_val.append('Something-Something-v2/lists/val_videofolder.txt')
            prefix.append('img_{:06d}.jpg')
        elif moda == 'Flow':
            root_data.append(ROOT_DATASET + 'Something-Something-v2/flow_images')
            filename_imglist_train.append('Something-Something-v2/lists/train_videofolder_flow.txt')
            filename_imglist_val.append('Something-Something-v2/lists/val_videofolder_flow.txt')
            prefix.append('flow_{}_{:05d}.jpg')
        else:
            raise NotImplementedError('no such modality:'+modality)
`

**Comment by Polkach** [comment]
Hi! We have extracted Flow frames using code from this repo: https://github.com/wizyoung/Optical-Flow-GPU-Docker
The organization of _train_videofolder_flow.txt_ is exactly the same as for _train_videofolder.txt_
For instance, the first row of _train_videofolder.txt_ is as follows:

> Holding_[something]_next_to_[something]/78687 54 19

And the first row of _train_videofolder_flow.txt_ is: 

> Holding_[something]_next_to_[something]/78687 53 19

So, the only difference is the number of frames (the first integer) since Optical Flow requires two consecutive frames for evaluation.

Finally, you need to specify your paths to txts and directories with images in ops/dataset_config.py
